
pipeline{
    agent any
    tools{
        maven 'M2_HOME'
        jfrog 'Jfrog remote cli'
    }

    stages{
        stage('maven '){
            steps{
            sh 'mvn clean validate install test package'
        }
        
    }

    stage('maven '){
            steps{
            sh 'mvn clean validate install test package'
        }
        
    }
}
}