
pipeline{
    agent any
    tools{
        maven 'M2_HOME'
        
    }

    stages{
        stage('maven build tool'){
            steps{
            sh 'mvn clean install'
        }
        
    }

}
}